### ISSUE TITLE
memory.registerread isn't implemented

### ISSUE THREAD

**Issue by Xkeeper0** [TASEmulators/fceux#304]
Specifically, the code here comments out the function with a "todo" marker:
https://github.com/TASVideos/fceux/blob/master/src/lua-engine.cpp#L5941

Ideally, it would be nice to have `memory.registerread()` able to return a value that would be the result of that read, to be able to hook certain addresses. `memory.registerwrite()` recently got that functionality.

The use case would be hooking writes to areas of memory that _can't_ be read or written to normally, such as PPU registers or the APU, or even arbitrary addresses. This would allow a Lua script to emulate / simulate external devices or addons.

(Previous versions of the documentation said that the value written was not passed to `memory.registerwrite` because "you could just read what was written with `memory.readbyte`", but in the case of hardware registers that wasn't possible)

**Comment by bbbradsmith** [comment]
I'm kinda curious what happens if we just uncomment it? memory_registerread does seem to have an implementation, at least at first glance.

**Comment by vadosnaprimer** [comment]
Doesn't seem to ever get called, judging by https://github.com/TASVideos/fceux/commit/3ab41b359cd21d51fdd810a2de77b39ed42baeb7

**Comment by fmahnke** [comment]
I took a shot at this: https://github.com/TASEmulators/fceux/compare/master...fmahnke:fceux:mem-reg-read?expand=1

I've tested it and it seems to work. If this implementation is okay, could
someone experienced with C/LUA interop review the
`lua-engine.cpp::memory_registerHook` situation? If I understand that code, I
think the change I made should be safe since the read/write LUA callbacks
have the same signature.

This change touches some busy CPU functions, so do I need to try to measure
performance before/after?

Another thing I would need to finish a PR is some guidance to all the
parts of user documentation where we need to add this function.

Aside:

`LuaMemHookType` has these members `LUAMEMHOOK_WRITE_SUB, 
LUAMEMHOOK_READ_SUB, LUAMEMHOOK_EXEC_SUB` that seem to have come with porting code from gens: https://github.com/TASEmulators/fceux/commit/3ab41b359cd21d51fdd810a2de77b39ed42baeb7

The function `MatchHookTypeToCPU` is there to set them, but as far
as I can tell, the `_SUB` members are not actually used. Can we remove
`MatchHookTypeToCPU` and the `_SUB` members? They're not hurting anything,
it's just unnecessary code to read when you're in that file.

**Comment by fmahnke** [comment]
These are the files in the repository with references to `registerwrite` that look related to documentation. I would think adding `registerread` would touch the same files.

```
web/files/{D3F1816D-0770-4257-98D2-A21456B07D28}.htm
web/help/LuaFunctionsList.html
web/help/js/hndsd.min.js
```

Are these generated, or updated manually? In particular, I'm not sure what the purpose of `hndsd.min.js` is or how to change it. I assume it's generated since it's minified JS.

**Comment by fmahnke** [comment]
@bbbradsmith @thor2016 Could I have your help with figuring out how to continue?

**Comment by bbbradsmith** [comment]
I am not able to contribute at this time.

**Comment by thor2016** [comment]
The changes seem to look ok. It would be nice to know how much this changes CPU usage. If you are using linux, I usually just run `top -H` so that I can see the individual thread CPU usage. As long a normal computer is not dropping frames it is probably ok. I have some ideas on how to make this a little faster, but it can wait until this is merged. To edit the help web files, you need to edit `./vc/Help/fceux.hnd` using a program called help n doc. It will autogenerated the web/help files and you copy the new ones in. There is a specific version of help n doc that is supposed to be used as well and which one that is currently escapes me. Go ahead and prep the pull request now and we can do the doc update later.

**Comment by thor2016** [comment]
Also, please post the lua script you are using to test.

**Comment by fmahnke** [comment]
CPU info:

```
Cpuinfo Version: 9.0.0
Vendor ID Raw: GenuineIntel
Hardware Raw:
Brand Raw: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Hz Advertised Friendly: 3.4000 GHz
Hz Actual Friendly: 3.9000 GHz
Hz Advertised: (3400000000, 0)
Hz Actual: (3900000000, 0)
Arch: X86_64
Bits: 64
Count: 8
Arch String Raw: x86_64
L1 Data Cache Size: 131072
L1 Instruction Cache Size: 131072
L2 Cache Size: 1048576
L2 Cache Line Size: 256
L2 Cache Associativity: 6
L3 Cache Size: 8388608
Stepping: 3
Model: 60
Family: 6
Processor Type:
Flags: abm, acpi, aes, aperfmperf, apic, arat, arch_perfmon, avx, avx2, bmi1, bmi2, bts, clflush, cmov, constant_tsc, cpuid, cpuid_fault, cx16, cx8, de, ds_cpl, dtes64, dtherm, dts, ept, ept_ad, erms, est, f16c, flexpriority, flush_l1d, fma, fpu, fsgsbase, fxsr, ht, ibpb, ibrs, ida, invpcid, invpcid_single, lahf_lm, lm, mca, mce, md_clear, mmx, monitor, movbe, msr, mtrr, nonstop_tsc, nopl, nx, osxsave, pae, pat, pbe, pcid, pclmulqdq, pdcm, pdpe1gb, pebs, pge, pln, pni, popcnt, pse, pse36, pti, pts, rdrand, rdrnd, rdtscp, rep_good, sdbg, sep, smep, smx, ss, ssbd, sse, sse2, sse4_1, sse4_2, ssse3, stibp, syscall, tm, tm2, tpr_shadow, tsc, tsc_adjust, tsc_deadline_timer, tscdeadline, vme, vmx, vnmi, vpid, x2apic, xsave, xsaveopt, xtopology, xtpr
```

CPU usage tests were performed without any tools or LUA scripts running.

top command: `top -H -b -p $(pgrep fceux)`

Before changes:
```
top - 15:39:21 up 52 days, 21:24,  1 user,  load average: 1.54, 1.40, 1.30
Threads:  12 total,   0 running,  12 sleeping,   0 stopped,   0 zombie
%Cpu(s):  5.6 us,  1.5 sy,  0.0 ni, 92.8 id,  0.1 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem :  15944.1 total,   2555.2 free,  11542.3 used,   1846.6 buff/cache
MiB Swap:   8192.0 total,   4128.6 free,   4063.4 used.   3848.1 avail Mem

    PID   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1103520   20   0 2012312 169384 102272 S   8.0   1.0   0:02.69 emulatorThread_
1103513   20   0 2012312 169384 102272 S   3.0   1.0   0:01.55 fceux
1103537    5 -15 2012312 169384 102272 S   0.7   1.0   0:00.18 SDLAudioP1
1103521   20   0 2012312 169384 102272 S   0.3   1.0   0:00.18 fceux:cs0
1103527   20   0 2012312 169384 102272 S   0.3   1.0   0:00.13 fceux:gdrv0
1103514   20   0 2012312 169384 102272 S   0.0   1.0   0:00.04 QXcbEventQueue
1103515   20   0 2012312 169384 102272 S   0.0   1.0   0:00.00 QDBusConnection
1103522   39  19 2012312 169384 102272 S   0.0   1.0   0:00.00 fceux:disk$0
1103523   20   0 2012312 169384 102272 S   0.0   1.0   0:00.00 fceux:sh0
1103524   39  19 2012312 169384 102272 S   0.0   1.0   0:00.00 fceux:shlo0
1103526   20   0 2012312 169384 102272 S   0.0   1.0   0:00.00 fceux:gdrv0
1103536   39  19 2012312 169384 102272 S   0.0   1.0   0:00.00 PulseHotplug
```

After changes:
```
top - 15:37:45 up 52 days, 21:22,  1 user,  load average: 1.59, 1.37, 1.28
Threads:  12 total,   0 running,  12 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.2 us,  1.9 sy,  0.0 ni, 91.7 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :  15944.1 total,   2432.5 free,  11612.2 used,   1899.4 buff/cache
MiB Swap:   8192.0 total,   4175.4 free,   4016.6 used.   3768.2 avail Mem

    PID   PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND
1103061   20   0 2012324 170056 102932 S   8.7   1.0   0:03.24 emulatorThread_
1103054   20   0 2012324 170056 102932 S   3.0   1.0   0:01.82 fceux
1103068   20   0 2012324 170056 102932 S   0.7   1.0   0:00.15 fceux:gdrv0
1103055   20   0 2012324 170056 102932 S   0.3   1.0   0:00.05 QXcbEventQueue
1103062   20   0 2012324 170056 102932 S   0.3   1.0   0:00.22 fceux:cs0
1103102    5 -15 2012324 170056 102932 S   0.3   1.0   0:00.20 SDLAudioP1
1103056   20   0 2012324 170056 102932 S   0.0   1.0   0:00.00 QDBusConnection
1103063   39  19 2012324 170056 102932 S   0.0   1.0   0:00.00 fceux:disk$0
1103064   20   0 2012324 170056 102932 S   0.0   1.0   0:00.00 fceux:sh0
1103065   39  19 2012324 170056 102932 S   0.0   1.0   0:00.00 fceux:shlo0
1103067   20   0 2012324 170056 102932 S   0.0   1.0   0:00.00 fceux:gdrv0
1103101   39  19 2012324 170056 102932 S   0.0   1.0   0:00.00 PulseHotplug
```

**Comment by fmahnke** [comment]
Here's a test Lua script:

```
function test_registerread(a, s, v)
    message = string.format("read addr $%04x size %d val $%02x\n", a, s, v)
    print(message)
    fi:write(message)
    fi:flush()
end

memory.registerread(0x0, 255, test_registerread)
memory.registerread(0x700, 255, test_registerread)
memory.registerread(0xc000, 4096, test_registerread)

fi = io.open("registerread.log", "w")

while (true) do
    FCEU.frameadvance()
end
```
