### ISSUE TITLE
macOS distribution is not from a verified developer

### ISSUE THREAD

**Issue by meshuggahtas** [TASEmulators/fceux#434]
**Describe the bug**
FCEUX cannot be opened on default (freshly installed) macOS until you allow running it from the Security & Privacy settings window.

**To Reproduce**
1. Try to run the program

**Expected behavior**
I can run the program

**Screenshots**
![VirtualBox_MACOS 1234_22_12_2021_07_45_15](https://user-images.githubusercontent.com/31288337/147048978-18a549eb-c335-4470-9fe2-79535c6b7a04.png)

**(please complete the following information):**
 - OS and Version: macOS Big Sur 11.0 (virtualized but not relevant to this issue)
 - Version of FCEUX used (QT or non-QT): FCEUX 2.5.0 Qt

**Additional context**
Allowing FCEUX to run:
1. Apple menu > System Preferences > Security & Privacy > General
2. Click on "Open Anyway" in the 2nd tab group, above the lock

**Comment by meshuggahtas** [comment]
For Windows x64, you need to click on More Info and Run anyway.

**Comment by mjbudd77** [comment]
In order to make the application be trusted by the macOS, I have to code sign it as an official approved macOS developer. I believe I have to make an account with apple and then register to be an approved application signer. This costs money which I am not willing to spend (after all this is just a hobby for me).  The work around you found is what I would have suggested. Also, you can install fceux 2.5.0 via homebrew (command is: brew install fceux) and that will not have any of those issues.

**Comment by meshuggahtas** [comment]
Oh, I was under the impression that open source applications can gain free "signed application on Apple" stuff.

I advise to note future users who will try to use this application that the application (AFAIK) doesn't contains malware and probably a link to your above post for explanation why this happens. You can close this issue I think.
