### ISSUE TITLE
BUG: Axelay NES Tech Demo running on Mapper 23 doesn't work

### ISSUE THREAD

**Issue by lonkelle** [TASEmulators/fceux#477]
This tech demo runs fine on Mesen. There's some problem with FCEUX emulating Mapper 23 exactly to get this working like it does on real hardware and Mesen.

YouTube of Emulation: https://www.youtube.com/watch?v=AA9zGxJij5g

Tech Demo ROM link (creator's Google Drive): https://drive.google.com/file/d/1O8QpTlegVoxHFxteGTNu9C88_wV44G9H/view

**Comment by negativeExponent** [comment]
Fceu expects prg to be power of two. This version of the ROM has a PRG of 48K which can cause mask issues when used. Considering it's mapper 23, it should be at least 64 or 32k. There is another version which has 32k prg and that works.
If there's a reason to run with this ROM version in fceu instead then modify initial prg loading in mapper 23 to load prg C000 and E000 at banks 4 and 5 respectively

**Comment by lonkelle** [comment]
@negativeExponent Ahhh, gotcha. I couldn’t find the 32KB version anywhere of this tech demo but I can modify the original in the way you described to try it out. 

But my question is, if 48KB runs on real hardware - why wouldn’t it be FCEUX’s goal to emulate the NES properly rather than “expecting” standardized chips / sizes and failing to run otherwise? Doesn’t that make it less accurate? 

If Mesen emulates this properly and FCEUX doesn’t. I would say that FCEUX should consider being more lax as is with real hardware to allow for emulating this properly. Or am I missing something?

Also, would you mind linking that demo that works on 32KB? I looked for it since I can’t change the NES header on a phone to make this version work?

**Comment by negativeExponent** [comment]
Use this.

[AxelayNES_64k_prg.nes.zip](https://github.com/TASEmulators/fceux/files/8238587/AxelayNES_64k_prg.nes.zip)

this is practically the same rom with the last 16K of PRG (banks 4/5) mirrorored to make PRG a total of 64K.

and here is the 32K prg version of the rom
[Axelay_32K.nes.zip](https://github.com/TASEmulators/fceux/files/8238591/Axelay_32K.nes.zip)
 
dunno which demo is the latest

**Comment by lonkelle** [comment]
The 64KB one which I assume you modified manually is the latest demo and it works perfectly in FCEUX. Thank you very much for doing that for me. ☺️ 

it’s a cool tech demo fs. But the reason I brought this issue up is because the official final demo on the dev’s Google Drive is 48KB (they added music). 🎉 

This demo plays fine in Mesen and not in FCEUX. The goal in making this ticket wasn’t to hack around to get the demo working (tho it’s hella cool) - but to discuss if FCEUX should properly emulate the 48KB version like Mesen does?

Is there any reason not to program logic to handle this rare use case just like Mesen does?

**Comment by lonkelle** [comment]
Should I close this or is this considered something FCEUX should emulate as the official **final demo** of this game (what the dev tweeted) uses this mapper in this way?

**Comment by zeromus** [comment]
It's not immediately clear how this WOULD work on a real NES.  What happens if the mapper chip requests an invalid rom bank number? Is another bank accessed? Is FF returned? With the pow2 implementations it's implicitly clear: high bits of the mapper chip output are disconnected. invalid rom banks return the valid rom bank with the disconnected bits masked off.

A 48k PRG rom with 8k banks could be organized all these ways
ABCDEFxx (x is disconnected, returns all FF or such)
ABCDEFAB (wrap around, I guess? not very hardware-realistical)
ABCDEFCD (EF selected by higher bit, but final two banks not patched on by higher bit, falling through to CD)

The VRC defaults to selecting rom bank $FF (which is surely invalid) for the final $Exxx-$Fxxx bank. 
So which bank is selected by that? x, B, or D? Note that none of those choices are the sensible "final" bank, which is probably expected to be F.

An actual REAL hardware device would probably be a 64KB rom with SOMETHING chosen to put in the end (F, probably).
It would actually be set up like this:
ABCDEFxF

So now I hope you see this isn't as simple as "do what the NES does". As far as I'm concerned, these NPOT mappers are illegal hacks until someone proves it otherwise by putting it on a physical cart. Then we can talk about how to emulate _that_ hardware.

**Comment by lonkelle** [comment]
@zeromus I really appreciate the insight, like, a lot. You're one of the rare few emu devs that is v nice, even when a user is wrong. Given your new info, I'm seeing this as more of a "It worked in MESEN and that's all that matters" homebrew dev situation (given most use MESEN for development). I incorrectly assumed if they were making a tech demo, they'd have tested it on real hardware - but it's v clear now the dev didn't do that.

They never released the final demo in the correct format (the final demo has music and is 48KB, sans music the rom is 32KB and works as expected) so I'll tweet them about it. negativeExponent was the one who padded it to get the final (music) version of the demo to work on FCEUX. 

As for detecting and padding the ROM, that seems doable. Open ROM -> ROM doesn't work -> FCEUX does a little test to determine if the cause is incorrect PRG ROM size and pads / fixes the file. Obviously this isn't a priority by any means since there's unlikely to many more instances of this exact situation happening in the homebrew dev world. But, the fact that MESEN runs the "official" ROM "as the dev intended" means this specific dev's mistake, well, other's may make the same one in the future. So fixing the ROMs rather than emulate incorrectly (MESEN, tsk) will be better for the community IMO.

**Comment by zeromus** [comment]
OK, I'm going to close this as "show me the hardware, and I'll emulate it"
