### ISSUE TITLE
[Bug] Cheats Window: cheat name gets garbled if you edit value.

### ISSUE THREAD

**Issue by ReyVGM** [TASEmulators/fceux#512]
Using FCEUX 2.6.4

If you add a cheat and try to edit its value while any cheat is disabled, the cheat's name will get changed to other characters.

-Open any game
-Add a couple random cheats (it could be 1111:00, it doesn't matter) and name it whatever you like.
-Disable one of the cheats and try to edit its **value**
-The name will auto change to a random character.

![Capture](https://user-images.githubusercontent.com/7338867/169264932-5230eb52-4f00-4cf0-8752-67b4d517084d.PNG)

**Comment by Vortaka** [comment]
I can attest to that!  Doesn't happen on all the games (Legend of Zelda I played a couple of days ago was ok, but it screwed punch out!).
Until fixed, I'll go back to 2.6.3!

**Comment by zeromus** [comment]
I believe this is due to FCEUI_SetCheat which can in principle strcpy to and from the same string depending on how the compiler's doing strcpy and other chaos PLUS ALSO how it's called from the cheat editor. If 'name' passed in is the same pointer as was just returned by FCEUI_GetCheat, and realloc decides to return the same pointer (because the length is the same, no reallocation is actually needed), then the strcpy will be on the same pointers

**Comment by zeromus** [comment]
OK, this should be fixed now. I started to just change it in FCEUI_SetCheat() to not do the unsafe strcpy but then I realized even the memory management was potentially troublesome (anyone who called FCEUI_GetCheat() to get a name may hold onto it even after calling FCEUI_SetCheat() without realizing that FCEUI_SetCheat may be FREEING IT!) and decided to just redo the cheat api with std::string instead. Of course this necessitated changing how CHEATF were memory-managed since it was done with malloc before and it needs to be done with `new` when using std::string

this will have broken the other frontends since the cheat FCEUI apis were changed.
