### ISSUE TITLE
[Glitch] Missing "polygonal" effect in Final Fantasy 1

### ISSUE THREAD

**Issue by ReyVGM** [TASEmulators/fceux#529]
**Describe the bug**
A grey polygonal-looking effect is missing when steeping into an altar.

**To Reproduce**
1. Step into an altar after you defeat a fiend.

**Expected behavior**
The screen should shake and a gray polygonal effect comes out of the altar and up to the top-left of the screen. This works correctly in Nestopia, but in FCEU, you only see the screen shaking.

**Screenshots**
(This shows how the effect should look. Used Nestopia)
![Final Fantasy (USA)_001](https://user-images.githubusercontent.com/7338867/174194783-481eeffe-1ed6-4fe2-9dee-a4e73339a00a.png)

**(please complete the following information):**
 - OS and Version: Win 7 64 bit
 - Version of FCEUX used (Version 2.6.4)

**Additional context**
Here's a FCEU save state right before the altar:
[Final Fantasy (USA).zip](https://github.com/TASEmulators/fceux/files/8923415/Final.Fantasy.USA.zip)

A the Nestopia save state right before the altar:
[Final Fantasy (USA) nestopia.zip](https://github.com/TASEmulators/fceux/files/8923419/Final.Fantasy.USA.nestopia.zip)

**Comment by zeromus** [comment]
This is caused by the color effect handling (deemph and grayscale) being done on a per-scanline basis. the game is changing the grayscale bit in PPUMASK twice in a scanline and leaving it clear at the end when the palette is applied.
RefreshLine() in ppu.cpp needs to be changed to have another buffer, besides "target" to "render" the deemph and monochrome bits to (check ResetRL() which initializes the render lines). That's for the old PPU of course but we should start there. Once the color effect bits are "rendered" then they can be used at these two points:
"//greyscale handling (mask some bits off the color) ? ? ?"
and
"//some pathetic attempts at deemph"
pathetic attempts were probably added for.. werewolf or something? I can't remember. Some game like that. Maybe the history shows.
Need to check history for notes about that and re-test that game.
Also if there's any known tests that change deemph on the fly for a similar effect to this FF "polygon" effect that would be helpful too

Despite the wall of text above this is actually not that hard a task. Probably any aspiring emudev can tackle it

**Comment by zeromus** [comment]
OK I fixed this for newppu. It wasn't setup to handle this properly, but I managed to find a way. As For oldppu... it's a lost cause.

**Comment by zeromus** [comment]
Hey can you do me a favor and check this on neshawk? I bet it's broken there, too, but I dont know how far alyosha and friends have advanced it. It's just... requiring a finer level of detail on the PPU timing than I've ever even thought about (the palette needs to be read on every PPU clock cycle... now actually I think it might not be legal to change that mid-line (conflicts with PPU reading it), but the _color effects_ it is definitely legal to change on the fly.

**Comment by ReyVGM** [comment]
Just tested it. Works fine on NEShawk. At least on the version included with Bizhawk 2.7 (November 2021).

**Comment by zeromus** [comment]
thanks. well, I guess our work here is done (damn, I should have checked how neshawk does it. oh well. it's done now)

**Comment by ReyVGM** [comment]
Haha, no problem. Thanks for the fix!
