### ISSUE TITLE
Missing hotkey option for Soft-Reset

### ISSUE THREAD

**Issue by negativeExponent** [TASEmulators/fceux#565]
as stated, soft-reset is missing in list of hotkey selections, just Power, Reset and Pause.

**Comment by ReyVGM** [comment]
There's no such thing as a "soft reset". There's only Power and Reset and reset is already the "soft reset" you're looking for.

**Comment by negativeExponent** [comment]
> There's no such thing as a "soft reset". There's only Power and Reset and reset is already the "soft reset" you're looking for.

not sure if your joking or not... in any case, I'm not laughing.

**Comment by thor2016** [comment]
The Qt/SDL GUI does have both a soft and hard reset. The soft reset just calls ResetNES like the win32 GUI does. The hard reset is more of a convenience function that will close and reload a rom from the disk. In doing so all memory is wiped and ROM is reset to what is in the file. Also a hard reset shuts down the SDL video, audio, and input drivers and then reinitializes them from scratch. That said, the Ctrl+R should probably actually be mapped to the soft reset (so that it matches the win32 more) and a different hot key be mapped to the hard reset. I will look into this.

**Comment by thor2016** [comment]
Fix in commit d0add7a6. Please verify all works as expected.

**Comment by ReyVGM** [comment]
Isn't the "hard reset" just the power button?

**Comment by mjbudd77** [comment]
I suppose on real hardware that would be true. But that is not what I see in the code. LoadGame does a lot more than just init the emulator core. It resets a lot of tool dialogs and all the SDL drivers. So it is not the same. Look at the code for yourself

**Comment by negativeExponent** [comment]
> Fix in commit [d0add7a](https://github.com/TASEmulators/fceux/commit/d0add7a609ec818b4bfb93ca586873b41847d3a9). Please verify all works as expected.

thanks. latest PR fixed soft-reset hotkey. TO make this ui section simple, there should probably be just Pause, Power and Reset (soft reset). Power here will not issue a rom reload, but instead just the emulators Power function (should be move as a separate Reload ROM like option or something.

in anycase, this issue is now fixed and can be closed

Thanks. Fun times in fceux with recent updates :D
