### ISSUE TITLE
Family keyboard stuff

### ISSUE THREAD

**Issue by adiee5** [TASEmulators/fceux#572]
**Describe the bug**
I hope this is a bug, not intended behavior, but the thing is that even if i press scroll lock to activate the family keyboard, while it registers them as family basic presses, it also detects keyboard button presses as an controller and as system hotkeys.

**To Reproduce**
1. Turn on Family keyboard in settings
2. press scroll lock
3. buttons assigned to controller and hotkeys do those actions alongside (or in some cases **instead of**) family keyboard key presses

**Expected behavior**
after i press scroll lock none of the keyboard button presses should be registered as presses on the controller nor as emulator hotkeys/shortcuts

**(please complete the following information):**
 - OS and Version: Windows 10
 - Version of FCEUX used (QT or non-QT): fresh installation 2.6.4 non-qt

**Additional context**
I have basically just downloaded this emulator. i moved here from Fceuxd sp for similar reason, but it looks like here the problem is even worse (in fceuxd sp it wasn't registering hotkeys, but only controller presses), but luckly this emulator is still in active development, so i hope it'll be fixed

**Comment by thor2016** [comment]
The Qt version does not have this issue. When the family keyboard is active, it disables all keyboard shortcuts for the main window (except for the FKB enable toggle shortcut). Shortcuts for other child windows are still active when those windows have input focus. Because it is possible to have a regular controller mapped to the keyboard and have the family keyboard active at the same time, it is not wrong behavior both to respond to key presses. However, you can clear all the button mappings on the controller if you want it to not respond to inputs. You can save controller button mappings to separate profiles that will allow you easily switch between configs. Also, you can just map controller 1 to an actual physical game pad so that the keyboard can be free for FKB use.

**Comment by adiee5** [comment]
@thor2016 so Scroll Lock not disabling the Controller input is intended behavior? well, that's bit pity, since having to manually switch off the controller in settings all the time isn't pretty comfortable... (unless there are shortcuts to this), but ok, thanks for helping a bit

**Comment by thor2016** [comment]
If you try the latest Qt dev build, this should be fixed for you.

**Comment by adiee5** [comment]
Thank you so much for fixing this 😄

**Comment by adiee5** [comment]
oh no, there's new Bug 😳 now it doesn't read some buttons

**Comment by thor2016** [comment]
write a new bug with which buttons you have issues with.

**Comment by adiee5** [comment]
well, that was quick, i was going to do that

**Comment by adiee5** [comment]
Ok, never mind, now it seems to work
