### ISSUE TITLE
Kickmaster Hacks Break the Emulator's Hack

### ISSUE THREAD

**Issue by BirdhouseInYourSoul** [TASEmulators/fceux#576]
I made a hack for Kickmaster, and it turns out any hack of this game hangs at the end of Stage 2 in FCEUX due to this emulator having a hardcoded hack for the game, which is tied to CRC and thus doesn't trigger on hacked ROMs.

The best solution I see is to fix whatever FCEUX bug necessitated this hack in the first place; it seems to relate to MMC3 scanline timing, perhaps an off-by-one error. I've noticed scanline timing errors in hacks of other MMC3 games (like Crystalis, which seems to have a similar hack in FCEUX to fix it).

**Comment by zeromus** [comment]
If it was so easy to fix it properly then it would not have needed a hack in the first place. You can rename this issue to "properly fix whatever necessitates kickmaster hack" and we'll reopen it for later but don't expect it to get fixed any time soon. If you are going to actually release this hack then I suppose we can let you add the CRC to fceux. It would be better to make a proper system for looking up hacks to apply to given CRCs via a datafile instead of having it in code (see for instance how bizhawk does it)
