### ISSUE TITLE
MacOS builds

### ISSUE THREAD

**Issue by ClusterM** [TASEmulators/fceux#601]
Can someone fix MacOS autobuilds? https://ci.appveyor.com/project/zeromus/fceux
I don't see any errors in the log.

**Comment by ClusterM** [comment]
It builds without any problems on my branch: https://github.com/ClusterM/fceux/actions/runs/3862678191/jobs/6584397365

**Comment by thor2016** [comment]
It looks like homebrew is trying to build Qt and its dependencies from source (which takes way longer than 1 hour), instead of pulling in binary pre-built packages. Looking at Qt on the homebrew site, it looks like homebrew has dropped pre-build support for the Catalina version of mac OS, makes sense since Apple has already announced that Catalina is end of life. I will see if appveyor will build on the next mac OS version instead (Big Sur).

**Comment by thor2016** [comment]
Fixed with commit 293fc7b67
