### ISSUE TITLE
Question about internal LUA vs linking to external library?

### ISSUE THREAD

**Issue by mdinslage** [TASEmulators/fceux#612]
I am the fceux package maintainer for Slackware.  I noticed that if lua-5.1 is not found during compiling it will just build its own internal version of lua.  I am just wondering if there is any benefit of linking to an external lua library or is the internal lua fine.  I like the idea of just using the internal lua since it makes the package more portable. 

Thanks.

**Comment by thor2016** [comment]
I don't think there is much difference either way. That said, I'm not sure what all the possible lua build options are. Install location for supporting lua runtime files and environment setup come to mind. If I had to pick, I'd say using the system installed lua is better because it is more configurable. I believe that the lua snapshot that fceux keeps is more for convenience for the auto builds and windows builds. Also, helps deal with obsolescence issues as there is no plan currently to upgrade to newer versions of lua.
