### ISSUE TITLE
[QT-version] debugger performance issue (broken commit between 2.4.0 and 2.5.0) 

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASEmulators/fceux#617]
I found an obscure bug using a low-powered laptop for testing.
The bug appeared between FCEUX 2.4.0 and 2.5.0 (only QT version affected)

Step-by-step:

1. Open FCEUX and run any ROM. You will see a good performance (~60 FPS)
2. Open Debug -> Debugger. 
The performance will drop to ~20 FPS, but this is normal for old low-powered CPUs like intel atom.
3. Close Debugger. You will see that FPS still low. 
And this will remain until you close FCEUX completely.

QFCEUX 2.5.0 before debugger start:
![2 5 0_before_debugger_start](https://user-images.githubusercontent.com/13199529/220184661-710b8a1b-e57d-4ad1-8f5f-97666b682793.png)

QFCEUX 2.5.0 after debugger closed:
![2 5 0_after_debugger_closed](https://user-images.githubusercontent.com/13199529/220184748-c078c882-02d0-42bb-9ad4-9c80a112cfb8.png)

QTFCEUX 2.4.0 does not have this problem.
Bug still present in 2.6.5

**Comment by thor2016** [comment]
I think this is because opening the debugger automatically starts the trace logger. This is because the step back one instruction debugger function requires the trace log history to function. If you open the trace logger window and turn it off, you will see the frame rate jump back up. The debugger itself should not use up much CPU at all. For people who don't care about the step back function, I could add an option to not auto-start the trace logger. The step back function will inhibit itself already when it detects that the trace logger is off.

**Comment by eugene-s-nesdev** [comment]
I just checked this. 
You are absolutely right - opening the debugger automatically starts the trace logger. 
This is the root of the performance problem i found.

But this behavior happens only in the QT version. 
The Win-version does not enable trace-logger automatically.

**Comment by thor2016** [comment]
I don't believe the win-version has step back debugger feature. I will add a menu option to the debugger menu that will give control of auto start of the trace logger.

**Comment by thor2016** [comment]
I added code to address this issue in commit [da05b56](https://github.com/TASEmulators/fceux/commit/da05b56cbad4398393258d47b91805f107bd74f6). If you want the trace logger to auto start on debugger open, you have to select it in the debugger menu. Also, closing the debugger will now turn off the trace logger if it was the one that started it.

**Comment by eugene-s-nesdev** [comment]
I tested the last commit and it works fine.
Thank you!
