### ISSUE TITLE
2A03 pulse volume 1 is silent

### ISSUE THREAD

**Issue by pinobatch** [TASEmulators/fceux#703]
**Describe the bug**
2A03 pulse volume 1 is played as silence.

**To Reproduce**
1. On Xubuntu 23.10, build FCEUX from source code
2. Download [All_pulse_volumes.zip](https://github.com/TASEmulators/fceux/files/14158710/All_pulse_volumes.zip), extract the NSF, and play it
3. Hear a series of dits and then a tone, several times
4. Hear no tone after 1 dit

**Expected behavior**
After 8 dits, a tone is played at volume 8. After 7 dits, volume 7. After 1 dit, volume 1. Mesen, NSFPlay, and PowerPak behave this way.

**Screenshots**
I'd provide the NSFPlay render, but I don't know if GitHub Issues supports any free audio file formats.

**(please complete the following information):**
 - OS and Version: Xubuntu 23.10 x86-64
 - Version of FCEUX used: 5495c7e Qt

**Comment by negativeExponent** [comment]
volume adjustments for sound channels needs "adjusting" since it can cause final volume to be zero. in this test case, pulse channel at 1 tick has value fo 1. based on this channel computation:
`(pulse vol * modifier) / 256`
will turn a pulse volume at '1' with a modifier of 255(max volume in audio settings) will result in 0, turning off that channel.

there is a case where a modifier value of 256 will skip these volume adjustments but that doesnt seem to be accesible through fceux' audio settings.

@zeromus @thor2016

**Comment by zeromus** [comment]
problem only on QT port (ConsoleSoundConf.cpp, around lines 175..)
